Feature/ember mocha 0.14 upgrade
ember-cli/ember-cli-mocha pull request #261
Opened 2018-07-08 18:55 UTC by jbryson3

- Upgraded the test-helper blueprint to ember-mocha 0.14 syntax
- Left the helpers blueprints in-place for backwards compatibility
  - On the fence about this one, it might be confusing to keep these unused blueprints in here without a deprecation warning
- Switched the tests to use the ember-mocha 0.14 syntax

2018-07-08 18:58 UTC, jbryson3 commented
I have tested these changes on a fresh ember init with ember-cli@3.1.4 - however, I'd really like to add some acceptance tests to this repo. Something akin to using `ember-cli-addon-tests` to simulate on a dummy app
- ember install ember-cli-mocha
- migrating to the new syntax
- have the dummy app run its set of tests

But so far that level of integration test has proven difficult

2018-07-10 10:21 UTC, Turbo87 reviewed
first of all thanks for working on this @jbryson3!

I think we can remove the old helpers from the `ember-cli-mocha` blueprint, but we should probably add a new `old-mocha-helpers` blueprint and copy them in there so that those that still use the older APIs have a way of generating them in the transition period.

Did you check that the new `test-helper.js` implementation using `setApplication()` also works fine when using the old APIs?

2018-07-17 16:54 UTC, jbryson3 commented
@Turbo87 I added the following sample tests in both the post 0.14 syntax, and the pre 0.14 syntax:
- Unit test
- Component Unit test
- Rendering test
- Model test
- Application test

2018-07-22 09:22 UTC, Turbo87 requested changes
@jbryson3 looks pretty good already

I got one more small change request though. Instead of using a `legacy-helpers` folder in the existing blueprint I think it would be better to have the helpers in the `helpers` folder of a dedicated `legacy-helpers` blueprint.

2018-07-28 18:56 UTC, jbryson3 commented on ember-cli-build.js
> +    }
5 of the Old Syntax Acceptance tests were failing without it.
```
not ok 9 Chrome 67.0 - Acceptance | application - Old Syntax Acceptance | application TestLoader Failures dummy/tests/application/application-test: could not be loaded
    ---
        message: >
            regeneratorRuntime is not defined
        stack: >
            ReferenceError: regeneratorRuntime is not defined
```
A quick google search said the fix was adding the polyfill https://github.com/babel/babel-preset-env/issues/340

2018-09-19 15:54 UTC, jbryson3 commented
This PR is failing tests for reasons not related to code. Do you know any way to kick off the tests again?

![image](https://user-images.githubusercontent.com/675098/45765325-c8d29300-bc02-11e8-9c9b-9a4e196c4022.png)

2018-09-20 12:45 UTC, Turbo87 commented
@jbryson3 I've restarted the build :)

2018-11-28 15:31 UTC, topaxi commented
What is the status on this? Can I help in any way? The build failure seems to be related to using node 4, which isn't used anymore on master.

2020-02-13 02:15 UTC, jbryson3 commented
Closing old pull request in a deprecated repo

2020-02-13 02:15 UTC, closed without merging